[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chess-ml-framework"
version = "0.1.0"
description = "Training Chess Bots with Various Machine Learning Techniques"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "chess",
    "pyyaml",
    "numpy",
    "tqdm",
    "matplotlib",
    "pandas",
    "pyarrow",
    "torch_geometric",
    "duckdb",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
